# Generated by Django 3.0.6 on 2020-05-26 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200526_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 26, 8, 57, 48, 189697)),
        ),
    ]
